-- Script para crear la tabla de usuarios
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) NOT NULL UNIQUE
);

-- Script para crear la tabla de prestamos
CREATE TABLE prestamos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    libro VARCHAR2(200) NOT NULL,
    fecha_prestamo DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_prestamos_usuarios FOREIGN KEY (id_usuario) REFERENCES usuarios(id)
);
