CREATE TABLE usuarios (
    id_usuario NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre     VARCHAR2(100) NOT NULL,
    email      VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE prestamos (
    id_prestamo   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario    NUMBER       NOT NULL,
    libro         VARCHAR2(200) NOT NULL,
    fecha_prestamo DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_prestamos_usuarios FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);

CREATE TABLE libros (
    id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo        VARCHAR2(200) NOT NULL UNIQUE,
    disponibilidad NUMBER DEFAULT 1 NOT NULL
);

INSERT INTO libros (titulo, disponibilidad) VALUES ('El Quijote', 5);
INSERT INTO libros (titulo, disponibilidad) VALUES ('Cien años de soledad', 3);
INSERT INTO libros (titulo, disponibilidad) VALUES ('1984', 10);
COMMIT;